In [29]:
name="Nithinsai"

In [1]:
import torch
print(torch.cuda.is_available())

False


In [2]:
# Access first coloumn
tensor=torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [3]:
# Same like numpy accessing
tensor[:,:]

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [4]:
#Slicing operations
tensor[:2,:] #First two rows

tensor([[10, 20, 30],
        [40, 50, 60]])

In [5]:
print(tensor[:,:2])

tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [6]:
tensor[1:3,1:3] # slicing

tensor([[50, 60],
        [80, 90]])

In [7]:
# Fancy indexing
#(0,1)-->20
#(2,2)-->90
selecting_elements=tensor[[0,2],[1,2]]
print(selecting_elements)

tensor([20, 90])


In [8]:
# boolean indexing
mask=tensor>=50
print(tensor[mask])

tensor([50, 60, 70, 80, 90])


In [9]:
# Changing or mutable via indexing

tensor[0,1]=25

In [10]:
tensor_copy=tensor[:3,:2]
tensor_copy

tensor([[10, 25],
        [40, 50],
        [70, 80]])

In [11]:
tensor_copy[0,1]=15
tensor_copy

tensor([[10, 15],
        [40, 50],
        [70, 80]])

In [12]:
tensor[:,0]=torch.tensor([100,400,700])

In [13]:
tensor

tensor([[100,  15,  30],
        [400,  50,  60],
        [700,  80,  90]])

In [14]:
indices=torch.tensor([0,2])
selected_rows=torch.index_select(tensor,dim=0,index=indices) # dim=0 only rows
print(selected_rows)

tensor([[100,  15,  30],
        [700,  80,  90]])


In [15]:
# reversing using flip
#print(tensor[::-1])
print(torch.flip(tensor,dims=(1,)))
print(torch.flip(tensor,dims=(0,)))


tensor([[ 30,  15, 100],
        [ 60,  50, 400],
        [ 90,  80, 700]])
tensor([[700,  80,  90],
        [400,  50,  60],
        [100,  15,  30]])


In [16]:
# Random numbers
random_tensor=torch.rand(10) # provides 10 random numbers between 0-1
random_tensor

tensor([0.0420, 0.0405, 0.3211, 0.8076, 0.3586, 0.3718, 0.0604, 0.9860, 0.8777,
        0.5184])

In [17]:
random_tensor=torch.rand(2,5,3) # 2 of (5,3) matrix
print(random_tensor)

tensor([[[0.0176, 0.3443, 0.3228],
         [0.4638, 0.0169, 0.7578],
         [0.0151, 0.0665, 0.0283],
         [0.3324, 0.3382, 0.3764],
         [0.9195, 0.6889, 0.2720]],

        [[0.9548, 0.6986, 0.7602],
         [0.8240, 0.8217, 0.3114],
         [0.3619, 0.0589, 0.0043],
         [0.8827, 0.5579, 0.6894],
         [0.0687, 0.2231, 0.3609]]])


In [18]:
torch.manual_seed(42)
random_tensor=torch.rand(10) # seed is given
random_tensor

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332])

In [19]:
# Generate Normal Integers
print(torch.randint(1,10,(5,3)))

tensor([[5, 5, 9],
        [1, 1, 5],
        [3, 5, 4],
        [5, 5, 9],
        [2, 6, 9]])


In [20]:
# Generate random numbers from normal distributions

# torch.normal(mean,std,size)
random_normal=torch.normal(1,2,(5,))
print(random_normal)

tensor([ 2.4979,  3.2328,  3.5862,  1.8274, -0.1420])


## Creating Noise image

In [21]:
import matplotlib.pyplot as plt

#h,w of image 256x256

uniform_noise=torch.rand(256,256) # between 0-1
plt.imshow(uniform_noise.numpy(),cmap='grey')
plt.title("Uniform noise image")

ModuleNotFoundError: No module named 'matplotlib'

In [22]:
uniform_noise_rgb=torch.rand(256,256,3) # between 0-1
plt.imshow(uniform_noise_rgb.numpy())
plt.title("Uniform noise image RGB")

NameError: name 'plt' is not defined

In [23]:
print(uniform_noise_rgb)

tensor([[[0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104],
         [0.9464, 0.7890, 0.2814],
         ...,
         [0.2230, 0.4166, 0.1630],
         [0.9885, 0.3997, 0.6986],
         [0.0535, 0.7878, 0.3446]],

        [[0.1197, 0.5731, 0.7422],
         [0.9327, 0.1946, 0.2539],
         [0.5961, 0.6356, 0.6922],
         ...,
         [0.4606, 0.3515, 0.4982],
         [0.6605, 0.4890, 0.5231],
         [0.5633, 0.6862, 0.3483]],

        [[0.2019, 0.6180, 0.4408],
         [0.2735, 0.7100, 0.5045],
         [0.4273, 0.2580, 0.4342],
         ...,
         [0.0263, 0.6988, 0.9117],
         [0.2242, 0.6348, 0.4420],
         [0.4818, 0.5291, 0.9333]],

        ...,

        [[0.4553, 0.9983, 0.9154],
         [0.7205, 0.0675, 0.9463],
         [0.3992, 0.5067, 0.7542],
         ...,
         [0.7451, 0.2902, 0.4987],
         [0.0369, 0.5494, 0.4745],
         [0.6425, 0.4817, 0.8017]],

        [[0.0119, 0.1018, 0.5591],
         [0.1722, 0.3210, 0.9809],
         [0.

In [24]:
# zeros and ones
zeros_tensor=torch.zeros(3,3,3)
print(zeros_tensor)
print(zeros_tensor.shape)
ones_tensor=torch.ones(3,3,3)
print(ones_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([3, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [25]:
# Data Types for tensors
"""
*float--for most deep learning task-->float32,float64,float16
*integers- for categorical data and indices-->int32,int64,int8
*Booleans-mask or logical operations
*Complex number- advanced computation-->complex64,complex128

*float16 is computationally efficient but precision is less
*float64 is more accurate but computationally heavy
"""

'\n*float--for most deep learning task-->float32,float64,float16\n*integers- for categorical data and indices-->int32,int64,int8\n*Booleans-mask or logical operations\n*Complex number- advanced computation-->complex64,complex128\n\n*float16 is computationally efficient but precision is less\n*float64 is more accurate but computationally heavy\n'

In [26]:
d=torch.tensor([1.5,2.5,3.5])
d.to(torch.float64)

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64)

In [27]:
b=torch.tensor([True,False,True,False])
b.to(torch.int)

tensor([1, 0, 1, 0], dtype=torch.int32)

## Impact of datatype on memory

In [28]:
float_32=torch.ones(1000,dtype=torch.float32)
float_64=torch.ones(1000,dtype=torch.float64)

#Tensor.element_size()-size of one element
# element_size()--> gives you size of one element in bytes

print("memory used by float32:",float_32.element_size()*float_32.nelement(),'bytes')
print("memory used by float32:",float_64.element_size()*float_64.nelement(),'bytes')

memory used by float32: 4000 bytes
memory used by float32: 8000 bytes


In [ ]:
#float32--> default for most NN models
#float64--> high precision computation
#int32--> general purpose integer
#int64--> tensor indices

## Tensor Manipulation

-Reshaping

-slicing

-joining or splitting

-transposing and permuting dimension

In [1]:
# reshaping tensors
#reshape and view
import torch

In [2]:
original_tensor=torch.arange(0,12,dtype=torch.float32)

In [15]:
original_tensor.reshape(4,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [21]:
secondary_t=torch.arange(12,24,dtype=torch.float32)
secondary_t.reshape(4,3)
torch.transpose(secondary_t)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [19]:
original_tensor.matmul(torch.transpose(secondary_t))


TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [20]:
original_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [25]:
#view
print(original_tensor.is_contiguous())
flattened=original_tensor.view(-1)
print(flattened)

True
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


## Joining Tensors

In [4]:
# torch.cat()--> Merges tensors along existing dimensions
first=torch.tensor([[1,2],[3,4]])
second=torch.tensor([[5,6],[7,8]])

con_rows=torch.cat((first,second),dim=0)
con_cols=torch.cat((first,second),dim=1)
print(con_rows)
print(con_cols)
print(con_rows.shape)
print(con_cols.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([4, 2])
torch.Size([2, 4])


In [5]:
# stack --> created a new dimension increases the tensor's rank

stack_rows=torch.stack((first,second),dim=0)
stack_cols=torch.stack((first,second),dim=1)
print(stack_rows.shape)
print(stack_cols.shape)
print(stack_rows)
print(stack_cols)

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


## Splitting tensors

torch.chunk()-->divides tensor into equal sized chunk

torch.split()-->allows uneven splitting as well

In [6]:
# torch.chunk
tensor=torch.arange(12)
chunk=torch.chunk(tensor,3,dim=0)
print(chunk)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))
